keys:
  - &admin_lyc age1tcz7npvfsevrwkxn7ymuju3whj8ekeupn6jwgmnfcfc4s74h7g3svr7dzy
  - &server_adrastea age18appjgzkrf5jnjjp5566e33lt0w3wtrg8e2yqzfltzd8n2l60ccs85xxrk
  - &machine_aplaz age1m7lgj74f7q02slnwj9aaw89t8q84242cjnvnua42esnvpwualp5svtx2ke
  - &machine_metis age1q3wrg2mx9rjv4qedplesu28gyu0j7rzf0zt95zw9xxn524llwyzstjqk3a
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin_lyc
      - *server_adrastea
      - *machine_aplaz
      - *machine_metis
