keys:
  - &admin_lyc age1tcz7npvfsevrwkxn7ymuju3whj8ekeupn6jwgmnfcfc4s74h7g3svr7dzy
  - &server_adrastea age18appjgzkrf5jnjjp5566e33lt0w3wtrg8e2yqzfltzd8n2l60ccs85xxrk
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin_lyc
      - *server_adrastea
